variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

image: maven:latest

stages:
  - build
  - test
  - package

cache:
  paths:
    - .m2/repository

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Maven compile started"
    - "mvn clean install"

test_job:
  stage: test
  tags:
    - docker
  script:
    - echo "Maven test started"
    - "mvn clean test"

package_job:
  stage: package
  tags:
    - docker
  script:
    - echo "Maven package started"
    - "mvn package"
