 spring:
    data:
        mongodb:
            database:  camera
            host : localhost
            port : 27017
 logging:
     level:
         org:
             springframework:
                 data:
                     mongodb:
                         core:
                             MongoTemplate: DEBUG
