version: "3.7"
services:
  mongo_db:
    image: mongo:latest
    restart: on-failure
    ports:
      - 27017:27017
  camera_service:
    build:
      context: ../../../
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
